### ISSUE TITLE
CMake: add a target with all headers?

### ISSUE THREAD

**Issue by sbastrakov** [ComputationalRadiationPhysics/llama#12]
I think it is convenient (at least for Visual Studio) to have a cmake target that just has all headers of the library, like [how alpaka does with alpakaIde](https://github.com/ComputationalRadiationPhysics/alpaka/blob/412ca629c3c28bb9de5666a286a81431a28fa12b/alpakaConfig.cmake#L677). Otherwise it is sometimes problematic to quickly navigate to a library file from VS.
Of course, that is just a matter of convenience and not a bug.

**Comment by sbastrakov** [comment]
Fair point.

**Comment by ax3l** [comment]
One can do this since we have to introduce a more general CMake target in #10. Ideally, we add these headers without a `file(GLOB ...)`, since that is [considered evil](https://stackoverflow.com/questions/1027247/is-it-better-to-specify-source-files-with-glob-or-each-file-individually-in-cmak).

**Comment by bernhardmgruber** [comment]
#34 added the target `llamaIde` that serves this purpose.
