### ISSUE TITLE
Re-Definable Control Defines

### ISSUE THREAD

**Issue by ax3l** [ComputationalRadiationPhysics/llama#16]
Forged out of https://github.com/ComputationalRadiationPhysics/llama/pull/15#discussion_r229648324:

Some `examples/` deploy `#define` vars for building them in variants.

I usually prefer to put such controls in a
```C++
#ifndef VAR
#define VAR default
#endif 
```
block so one can control them without warnings externally.

**Comment by bernhardmgruber** [comment]
I changed almost all such constants into `constexpr` variables so this suggestion no longer applies. Furthermore, I think the examples are intended for users to play inside the source code and not steer parameters on the compiler command line ;)
